name: Release Flow
on:
  push:
    branches:
      - 'development'
jobs:
  release-on-merge:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions: write-all
    # needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # actions by github to checkout repository
        with:
          fetch-depth: 0
      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: '~/.npm'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: Derive appropriate SHAs for base and head for `nx affected`
        uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: 'development'
      - name: Npm install
        run: npm ci
      - name: Build realise bundle
        run: npx nx affected -t build
      - name: Create release
        run: npx nx affected -t release --branches=development --parallel=1
      - name: Upload bundle artifact
        uses: actions/upload-artifact@v3
        with:
          path: 'dist'
          name: ${{ env.name }}-artifact
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
