name: Test Workflow
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3  # actions by github to checkout repository
      - name: Npm install
        run: npm ci
      - name: Build affected
        run: nx affected -t build
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@3  # actions by github to checkout repository
      - name: Npm install
        run: npm ci
      - name: Create release
        run: nx affected -t release --parallel=1
